"""All server-rendered text (SEO copy, guide, FAQ, legal pages) in the five languages.
Edit here to change wording. The speed-test interface strings live in templates/index.html (I18N block)."""

LANGS = ['ar', 'en', 'tr', 'fr', 'fa']
NAMES = {'ar': 'العربية', 'en': 'English', 'tr': 'Türkçe', 'fr': 'Français', 'fa': 'فارسی'}
RTL = {'ar', 'fa'}
OG_LOCALE = {'ar': 'ar_AR', 'en': 'en_US', 'tr': 'tr_TR', 'fr': 'fr_FR', 'fa': 'fa_IR'}
PAGES = ['about', 'privacy', 'terms', 'contact']
UPDATED = '2026-09-30'

# placeholders usable inside any text: {site} {email} {operator}
T = {}

# ------------------------------------------------------------------ ENGLISH
T['en'] = {
    'title': 'Internet Speed Test - Free Download, Upload & Ping Test',
    'desc': 'Test your internet speed in about 30 seconds. Free, accurate download, upload, ping and jitter test that also shows your IP, provider and connection type.',
    'h1': 'Internet Speed Test',
    'sub': 'Measure your download speed, upload speed, ping and jitter in about 30 seconds.',
    'nav': {'home': 'Speed test', 'about': 'About', 'privacy': 'Privacy policy', 'terms': 'Terms of use', 'contact': 'Contact'},
    'ui': {'skip': 'Skip to content', 'ad': 'Advertisement', 'rights': 'All rights reserved', 'server': 'Server', 'lang': 'Language',
           'to_light': 'Switch to light mode', 'to_dark': 'Switch to dark mode', 'updated': 'Last updated', 'back': 'Back to the speed test',
           'notfound': 'Page not found', 'notfound_p': 'The page you are looking for does not exist.', 'menu': 'Menu'},
    'guide_title': 'Understanding your speed test result',
    'guide': [
        ('What do Mbps download and upload mean?',
         'Speeds are measured in megabits per second (Mbps). Download speed is how fast data reaches your device - it matters for streaming, browsing and downloading files. Upload speed is how fast your device sends data out - it matters for video calls, cloud backups and sending large files.'),
        ('What are ping and jitter?',
         'Ping is the time, in milliseconds (ms), a small message takes to travel to the server and back. Jitter is how much that time changes from one message to the next. Low ping and low jitter feel responsive in games, calls and remote work. Under 50 ms is good for most things; jitter under 10 ms is very stable.'),
        ('How much speed do I need?',
         'Around 5 Mbps is enough for HD video on one screen, 15-25 Mbps handles 4K streaming, and 25-50 Mbps suits a busy household with video calls and cloud gaming. For working from home, upload speed of at least 10 Mbps keeps video meetings smooth.'),
        ('How to get the most accurate result',
         'Close other apps and downloads, pause streaming on other devices, and stay close to your router or use a cable. Run the test two or three times and compare. This test measures the speed between your device and our server, so results can differ slightly from other tools that use different servers.'),
    ],
    'faq_title': 'Frequently asked questions',
    'faq': [
        ('Is this speed test free?', 'Yes. The test is completely free and needs no sign-up or app.'),
        ('Why is my speed lower than what my provider promises?', 'Providers advertise the best-case speed of your plan. Wi-Fi quality, distance from the router, busy hours, old devices and the test server location can all lower the result. Testing with a cable shows what your line can really deliver.'),
        ('How much data does the test use?', 'A full test can use roughly 100-300 MB on a fast connection and less on a slow one. If you are on mobile data with a limited plan, run it only when needed.'),
        ('Can the test see my Wi-Fi name?', 'No. Browsers do not allow any website to read your Wi-Fi name. The site shows your IP address, provider and approximate location, and detects whether you are on Wi-Fi, cable or mobile data where your browser allows it.'),
    ],
    'pages': {
        'about': {'title': 'About {site}', 'desc': 'What {site} is and how the internet speed test works.', 'body': [
            ('p', '{site} is a free internet speed test. It measures download speed, upload speed, ping and jitter, and shows your IP address, internet provider, approximate location and connection type.'),
            ('h', 'How the test works'),
            ('p', 'The test first measures latency with a series of small requests. It then opens six parallel connections to our server and transfers random data, first downloading and then uploading. The first seconds are ignored because connections are still warming up; the final number is the average speed after that. The dial shows the live speed while the test runs.'),
            ('h', 'Who runs it'),
            ('p', 'The site is operated by {operator}. It is free to use and supported by advertising. We do not sell personal data.'),
            ('h', 'Languages and appearance'),
            ('p', 'The site is available in Arabic, English, Turkish, French and Persian, with light and dark modes.'),
        ]},
        'contact': {'title': 'Contact us', 'desc': 'Contact the {site} team for questions, bug reports or business enquiries.', 'body': [
            ('p', 'Questions, suggestions or bug reports? Write to us at {email}.'),
            ('p', 'When reporting a problem, please tell us your browser and device and, if possible, paste the text from the "Test details" box under your result. It helps us find the cause quickly.'),
            ('p', 'We read every message but cannot provide support for your internet provider or router.'),
        ]},
        'privacy': {'title': 'Privacy policy', 'desc': 'How {site} handles your data: IP address, cookies and advertising.', 'body': [
            ('p', 'This policy explains what information {site} processes when you use the website.'),
            ('h', 'Information we process'),
            ('p', 'When you open the site we process your IP address. We show it back to you and use it to look up your internet provider and approximate location. For this lookup your IP address is sent to third-party services (ipapi.is, ipwho.is, ipapi.co). The result is kept in server memory for up to one hour and is not saved in a database or linked to your identity.'),
            ('h', 'Speed test data'),
            ('p', 'The test transfers random data between your device and our server. Nothing in it is stored. Results are displayed in your browser and are copied only if you press the copy button. Your browser may use WebRTC locally to detect whether you are on Wi-Fi, cable or mobile data; no addresses are sent anywhere.'),
            ('h', 'Cookies and local storage'),
            ('p', 'We store your language and theme choice in your browser (a cookie named st_lang and local-storage entries st_lang and st_theme). They only remember your settings and contain no personal data.'),
            ('h', 'Advertising'),
            ('p', 'We use Google AdSense to show ads. Google and its partners may use cookies or similar technologies to show personalised or non-personalised ads based on your visits to this and other websites. You can learn how Google uses data at https://policies.google.com/technologies/partner-sites and manage ad personalisation at https://adssettings.google.com. Visitors from the European Economic Area, the United Kingdom and Switzerland are asked for consent before personalised ads are shown.'),
            ('h', 'Server logs'),
            ('p', 'Our hosting provider may keep standard server logs (IP address, time and requested page) for security and operation of the service.'),
            ('h', 'Your rights'),
            ('p', 'Depending on where you live you may have the right to access, correct or delete personal data or to object to its processing. Contact us at {email} and we will respond.'),
            ('h', 'Children'),
            ('p', 'The site is not directed at children under 13 and we do not knowingly collect their data.'),
            ('h', 'Changes'),
            ('p', 'We may update this policy. The date at the top shows the latest version.'),
        ]},
        'terms': {'title': 'Terms of use', 'desc': 'Terms for using the {site} internet speed test.', 'body': [
            ('p', 'By using {site} you agree to these terms.'),
            ('h', 'The service'),
            ('p', 'The speed test is provided free of charge and "as is", without guarantees of availability or accuracy.'),
            ('h', 'Accuracy of results'),
            ('p', 'Results depend on your device, browser, Wi-Fi quality, your provider and the distance to our server. They show the speed between your device and our server and may differ from other tools. They should not be used as legal proof of your provider\'s performance.'),
            ('h', 'Acceptable use'),
            ('p', 'Do not use scripts, bots or repeated requests to overload the service or to consume bandwidth. To protect the service we limit the amount of test data each connection can use per hour, and we may block abusive traffic.'),
            ('h', 'Advertising and links'),
            ('p', 'The site shows third-party ads. We are not responsible for the content or practices of advertisers or linked websites.'),
            ('h', 'Liability'),
            ('p', 'To the extent permitted by law, {site} is not liable for any loss arising from the use of, or inability to use, the service.'),
            ('h', 'Changes'),
            ('p', 'We may change these terms at any time. Continued use means you accept the updated terms.'),
        ]},
    },
}

# ------------------------------------------------------------------ ARABIC
T['ar'] = {
    'title': 'فحص سرعة الإنترنت - اختبار التنزيل والرفع والبنق مجاناً',
    'desc': 'افحص سرعة الإنترنت لديك خلال 30 ثانية تقريباً. اختبار مجاني ودقيق للتنزيل والرفع والبنق والتذبذب، ويعرض عنوان IP ومزوّد الخدمة ونوع الاتصال.',
    'h1': 'فحص سرعة الإنترنت',
    'sub': 'قِس سرعة التنزيل والرفع والبنق والتذبذب خلال 30 ثانية تقريباً.',
    'nav': {'home': 'فحص السرعة', 'about': 'من نحن', 'privacy': 'سياسة الخصوصية', 'terms': 'شروط الاستخدام', 'contact': 'اتصل بنا'},
    'ui': {'skip': 'تخطَّ إلى المحتوى', 'ad': 'إعلان', 'rights': 'جميع الحقوق محفوظة', 'server': 'الخادم', 'lang': 'اللغة',
           'to_light': 'التبديل إلى الوضع الفاتح', 'to_dark': 'التبديل إلى الوضع الداكن', 'updated': 'آخر تحديث', 'back': 'العودة إلى فحص السرعة',
           'notfound': 'الصفحة غير موجودة', 'notfound_p': 'الصفحة التي تبحث عنها غير موجودة.', 'menu': 'القائمة'},
    'guide_title': 'كيف تفهم نتيجة فحص السرعة',
    'guide': [
        ('ماذا تعني سرعة التنزيل والرفع (Mbps)؟',
         'تُقاس السرعة بالميغابت في الثانية (Mbps). سرعة التنزيل هي سرعة وصول البيانات إلى جهازك، وتهمّ في مشاهدة الفيديو وتصفح المواقع وتحميل الملفات. سرعة الرفع هي سرعة إرسال البيانات من جهازك، وتهمّ في مكالمات الفيديو والنسخ الاحتياطي السحابي وإرسال الملفات الكبيرة.'),
        ('ما هو البنق والتذبذب؟',
         'البنق هو الزمن بالميلي ثانية (ms) الذي تستغرقه رسالة صغيرة للوصول إلى الخادم والعودة. والتذبذب هو مقدار تغيّر هذا الزمن من رسالة إلى أخرى. كلما انخفض البنق والتذبذب كان الاتصال أكثر استجابة في الألعاب والمكالمات والعمل عن بُعد. بنق أقل من 50 ms جيد لمعظم الاستخدامات، وتذبذب أقل من 10 ms يعني اتصالاً مستقراً جداً.'),
        ('كم سرعة أحتاج؟',
         'حوالي 5 Mbps تكفي لفيديو HD على شاشة واحدة، و15-25 Mbps تكفي لبث 4K، و25-50 Mbps تناسب منزلاً مزدحماً بمكالمات الفيديو والألعاب السحابية. وللعمل من المنزل تحتاج سرعة رفع لا تقل عن 10 Mbps ليبقى اجتماع الفيديو سلساً.'),
        ('كيف تحصل على نتيجة أدق',
         'أغلق التطبيقات والتحميلات الأخرى، وأوقف البث على الأجهزة الأخرى، واقترب من الراوتر أو استخدم كيبل. كرّر الفحص مرتين أو ثلاثاً وقارن. يقيس هذا الفحص السرعة بين جهازك وخادمنا، لذلك قد تختلف النتيجة قليلاً عن أدوات أخرى تستخدم خوادم مختلفة.'),
    ],
    'faq_title': 'الأسئلة الشائعة',
    'faq': [
        ('هل فحص السرعة مجاني؟', 'نعم، الفحص مجاني بالكامل ولا يحتاج تسجيلاً ولا تطبيقاً.'),
        ('لماذا سرعتي أقل مما وعدني به مزوّد الخدمة؟', 'تعلن الشركات أعلى سرعة لباقتك. وقد تقلّلها جودة الواي فاي والبعد عن الراوتر وأوقات الذروة والأجهزة القديمة وموقع خادم الفحص. الفحص عبر الكيبل يُظهر ما يستطيع خطك تقديمه فعلاً.'),
        ('كم يستهلك الفحص من البيانات؟', 'قد يستهلك الفحص الكامل نحو 100-300 ميجابايت على اتصال سريع، وأقل على الاتصال البطيء. إذا كنت على بيانات الهاتف بباقة محدودة فاستخدمه عند الحاجة فقط.'),
        ('هل يستطيع الموقع معرفة اسم شبكة الواي فاي؟', 'لا، المتصفحات لا تسمح لأي موقع بقراءة اسم شبكة الواي فاي. يعرض الموقع عنوان IP ومزوّد الخدمة والموقع التقريبي، ويحدد إن كنت على واي فاي أو كيبل أو بيانات الهاتف حيث يسمح متصفحك بذلك.'),
    ],
    'pages': {
        'about': {'title': 'من نحن - {site}', 'desc': 'ما هو {site} وكيف يعمل فحص سرعة الإنترنت.', 'body': [
            ('p', '{site} أداة مجانية لفحص سرعة الإنترنت. تقيس سرعة التنزيل والرفع والبنق والتذبذب، وتعرض عنوان IP ومزوّد الخدمة والموقع التقريبي ونوع الاتصال.'),
            ('h', 'كيف يعمل الفحص'),
            ('p', 'يقيس الفحص أولاً زمن الاستجابة عبر سلسلة طلبات صغيرة، ثم يفتح ستة اتصالات متوازية مع خادمنا وينقل بيانات عشوائية: تنزيلاً ثم رفعاً. تُهمل الثواني الأولى لأن الاتصالات لا تزال تتهيأ، والرقم النهائي هو متوسط السرعة بعد ذلك. وتعرض الساعة السرعة الحالية أثناء الفحص.'),
            ('h', 'من يشغّل الموقع'),
            ('p', 'يُدار الموقع بواسطة {operator}. استخدامه مجاني ويُموَّل بالإعلانات. نحن لا نبيع بيانات شخصية.'),
            ('h', 'اللغات والمظهر'),
            ('p', 'الموقع متاح بالعربية والإنجليزية والتركية والفرنسية والفارسية، مع الوضعين الفاتح والداكن.'),
        ]},
        'contact': {'title': 'اتصل بنا', 'desc': 'تواصل مع فريق {site} للاستفسارات أو الإبلاغ عن مشكلة أو الأعمال.', 'body': [
            ('p', 'لديك سؤال أو اقتراح أو مشكلة؟ راسلنا على {email}.'),
            ('p', 'عند الإبلاغ عن مشكلة اذكر المتصفح والجهاز، ويفضّل لصق النص الموجود في مربع «تفاصيل الاختبار» أسفل النتيجة، فهذا يساعدنا على معرفة السبب بسرعة.'),
            ('p', 'نقرأ كل الرسائل، لكننا لا نقدّم دعماً لمزوّد الإنترنت أو الراوتر لديك.'),
        ]},
        'privacy': {'title': 'سياسة الخصوصية', 'desc': 'كيف يتعامل {site} مع بياناتك: عنوان IP وملفات الكوكيز والإعلانات.', 'body': [
            ('p', 'توضّح هذه السياسة المعلومات التي يعالجها {site} عند استخدامك للموقع.'),
            ('h', 'المعلومات التي نعالجها'),
            ('p', 'عند فتح الموقع نعالج عنوان IP الخاص بك. نعرضه لك ونستخدمه لمعرفة مزوّد الإنترنت والموقع التقريبي. ولهذا الغرض يُرسل عنوان IP إلى خدمات خارجية (ipapi.is وipwho.is وipapi.co). تُحفظ النتيجة في ذاكرة الخادم مدة تصل إلى ساعة ولا تُخزَّن في قاعدة بيانات ولا تُربط بهويتك.'),
            ('h', 'بيانات فحص السرعة'),
            ('p', 'ينقل الفحص بيانات عشوائية بين جهازك وخادمنا ولا يُخزَّن منها شيء. تُعرض النتائج في متصفحك ولا تُنسخ إلا إذا ضغطت زر النسخ. قد يستخدم متصفحك تقنية WebRTC محلياً لمعرفة إن كنت على واي فاي أو كيبل أو بيانات هاتف، ولا تُرسل أي عناوين إلى أي جهة.'),
            ('h', 'ملفات الكوكيز والتخزين المحلي'),
            ('p', 'نحفظ اختيارك للغة والمظهر في متصفحك (كوكي باسم st_lang وعنصرا تخزين محلي st_lang وst_theme). وظيفتها تذكّر إعداداتك فقط ولا تحتوي على بيانات شخصية.'),
            ('h', 'الإعلانات'),
            ('p', 'نستخدم Google AdSense لعرض الإعلانات. قد تستخدم Google وشركاؤها ملفات الكوكيز أو تقنيات مشابهة لعرض إعلانات مخصصة أو غير مخصصة بناءً على زياراتك لهذا الموقع ومواقع أخرى. يمكنك معرفة كيف تستخدم Google البيانات عبر https://policies.google.com/technologies/partner-sites وإدارة تخصيص الإعلانات عبر https://adssettings.google.com. يُطلب من زوار المنطقة الاقتصادية الأوروبية والمملكة المتحدة وسويسرا الموافقة قبل عرض الإعلانات المخصصة.'),
            ('h', 'سجلات الخادم'),
            ('p', 'قد يحتفظ مزوّد الاستضافة بسجلات خادم اعتيادية (عنوان IP والوقت والصفحة المطلوبة) لأغراض الأمان وتشغيل الخدمة.'),
            ('h', 'حقوقك'),
            ('p', 'بحسب مكان إقامتك قد يحق لك الاطلاع على بياناتك الشخصية أو تصحيحها أو حذفها أو الاعتراض على معالجتها. راسلنا على {email} وسنردّ عليك.'),
            ('h', 'الأطفال'),
            ('p', 'الموقع غير موجّه للأطفال دون 13 عاماً ولا نجمع بياناتهم عن علم.'),
            ('h', 'التغييرات'),
            ('p', 'قد نحدّث هذه السياسة. يوضّح التاريخ في أعلاها آخر نسخة.'),
        ]},
        'terms': {'title': 'شروط الاستخدام', 'desc': 'شروط استخدام فحص سرعة الإنترنت في {site}.', 'body': [
            ('p', 'باستخدامك {site} فإنك توافق على هذه الشروط.'),
            ('h', 'الخدمة'),
            ('p', 'يُقدَّم فحص السرعة مجاناً وكما هو، دون ضمان للتوفر أو الدقة.'),
            ('h', 'دقة النتائج'),
            ('p', 'تعتمد النتائج على جهازك ومتصفحك وجودة الواي فاي ومزوّد الخدمة والمسافة إلى خادمنا. وهي تُظهر السرعة بين جهازك وخادمنا وقد تختلف عن أدوات أخرى، ولا يجوز اعتبارها دليلاً قانونياً على أداء مزوّد الخدمة.'),
            ('h', 'الاستخدام المقبول'),
            ('p', 'يُمنع استخدام السكربتات أو البوتات أو الطلبات المتكررة لإرهاق الخدمة أو استهلاك النطاق. ولحماية الخدمة نحدّ من كمية بيانات الفحص التي يستهلكها كل اتصال في الساعة، وقد نحجب الزيارات المسيئة.'),
            ('h', 'الإعلانات والروابط'),
            ('p', 'يعرض الموقع إعلانات من أطراف خارجية. لسنا مسؤولين عن محتوى المعلنين أو المواقع المرتبطة أو ممارساتهم.'),
            ('h', 'المسؤولية'),
            ('p', 'بالقدر الذي يسمح به القانون، لا يتحمل {site} مسؤولية أي خسارة ناتجة عن استخدام الخدمة أو عدم القدرة على استخدامها.'),
            ('h', 'التغييرات'),
            ('p', 'قد نغيّر هذه الشروط في أي وقت، واستمرارك في الاستخدام يعني قبولك للشروط المحدّثة.'),
        ]},
    },
}

# ------------------------------------------------------------------ TURKISH
T['tr'] = {
    'title': 'İnternet Hız Testi - Ücretsiz İndirme, Yükleme ve Ping Testi',
    'desc': 'İnternet hızınızı yaklaşık 30 saniyede ölçün. İndirme, yükleme, ping ve titreşimi ölçen; IP adresinizi, sağlayıcınızı ve bağlantı türünüzü gösteren ücretsiz hız testi.',
    'h1': 'İnternet Hız Testi',
    'sub': 'İndirme hızını, yükleme hızını, ping ve titreşimi yaklaşık 30 saniyede ölçün.',
    'nav': {'home': 'Hız testi', 'about': 'Hakkımızda', 'privacy': 'Gizlilik politikası', 'terms': 'Kullanım koşulları', 'contact': 'İletişim'},
    'ui': {'skip': 'İçeriğe geç', 'ad': 'Reklam', 'rights': 'Tüm hakları saklıdır', 'server': 'Sunucu', 'lang': 'Dil',
           'to_light': 'Açık moda geç', 'to_dark': 'Koyu moda geç', 'updated': 'Son güncelleme', 'back': 'Hız testine dön',
           'notfound': 'Sayfa bulunamadı', 'notfound_p': 'Aradığınız sayfa mevcut değil.', 'menu': 'Menü'},
    'guide_title': 'Hız testi sonucunu anlamak',
    'guide': [
        ('Mbps olarak indirme ve yükleme ne demek?',
         'Hız, saniyedeki megabit (Mbps) olarak ölçülür. İndirme hızı, verinin cihazınıza ne kadar hızlı ulaştığıdır; video izleme, gezinme ve dosya indirmede önemlidir. Yükleme hızı, cihazınızın veriyi ne kadar hızlı gönderdiğidir; görüntülü görüşme, bulut yedekleme ve büyük dosya göndermede önemlidir.'),
        ('Ping ve titreşim (jitter) nedir?',
         'Ping, küçük bir mesajın sunucuya gidip gelmesi için gereken süredir (milisaniye, ms). Titreşim ise bu sürenin mesajdan mesaja ne kadar değiştiğidir. Düşük ping ve düşük titreşim; oyunlarda, görüşmelerde ve uzaktan çalışmada akıcı bir deneyim verir. 50 ms altı çoğu iş için iyidir; 10 ms altı titreşim çok kararlıdır.'),
        ('Ne kadar hıza ihtiyacım var?',
         'Tek ekranda HD video için yaklaşık 5 Mbps yeterlidir, 4K yayın için 15-25 Mbps, görüntülü görüşme ve bulut oyunun olduğu kalabalık bir ev için 25-50 Mbps uygundur. Evden çalışırken görüntülü toplantıların akıcı olması için en az 10 Mbps yükleme hızı gerekir.'),
        ('En doğru sonucu nasıl alırsınız?',
         'Diğer uygulamaları ve indirmeleri kapatın, diğer cihazlardaki yayınları durdurun, modeme yakın durun veya kablo kullanın. Testi iki üç kez yapıp karşılaştırın. Bu test, cihazınız ile sunucumuz arasındaki hızı ölçer; bu yüzden farklı sunucular kullanan diğer araçlardan biraz farklı sonuç verebilir.'),
    ],
    'faq_title': 'Sık sorulan sorular',
    'faq': [
        ('Bu hız testi ücretsiz mi?', 'Evet. Test tamamen ücretsizdir; kayıt veya uygulama gerektirmez.'),
        ('Hızım neden operatörümün vaat ettiğinden düşük?', 'Operatörler paketinizin en iyi durumdaki hızını duyurur. Wi-Fi kalitesi, modemden uzaklık, yoğun saatler, eski cihazlar ve test sunucusunun konumu sonucu düşürebilir. Kabloyla test, hattınızın gerçekten ne sunduğunu gösterir.'),
        ('Test ne kadar veri kullanır?', 'Hızlı bir bağlantıda tam bir test yaklaşık 100-300 MB kullanabilir, yavaş bağlantıda daha az. Sınırlı mobil veri paketindeyseniz yalnızca gerektiğinde çalıştırın.'),
        ('Site Wi-Fi adımı görebilir mi?', 'Hayır. Tarayıcılar hiçbir web sitesinin Wi-Fi adını okumasına izin vermez. Site IP adresinizi, sağlayıcınızı ve yaklaşık konumunuzu gösterir; tarayıcınızın izin verdiği yerde Wi-Fi, kablo veya mobil veri kullandığınızı algılar.'),
    ],
    'pages': {
        'about': {'title': 'Hakkımızda - {site}', 'desc': '{site} nedir ve internet hız testi nasıl çalışır.', 'body': [
            ('p', '{site}, ücretsiz bir internet hız testidir. İndirme hızını, yükleme hızını, ping ve titreşimi ölçer; IP adresinizi, internet sağlayıcınızı, yaklaşık konumunuzu ve bağlantı türünüzü gösterir.'),
            ('h', 'Test nasıl çalışır'),
            ('p', 'Test önce küçük isteklerle gecikmeyi ölçer. Ardından sunucumuza altı paralel bağlantı açar ve rastgele veri aktarır: önce indirme, sonra yükleme. Bağlantılar hâlâ ısındığı için ilk saniyeler yok sayılır; nihai sayı bundan sonraki ortalama hızdır. Kadran, test sürerken anlık hızı gösterir.'),
            ('h', 'Kim işletiyor'),
            ('p', 'Site {operator} tarafından işletilmektedir. Kullanımı ücretsizdir ve reklamlarla desteklenir. Kişisel verileri satmayız.'),
            ('h', 'Diller ve görünüm'),
            ('p', 'Site Arapça, İngilizce, Türkçe, Fransızca ve Farsça olarak, açık ve koyu modla sunulur.'),
        ]},
        'contact': {'title': 'İletişim', 'desc': 'Sorular, hata bildirimleri veya iş teklifleri için {site} ekibiyle iletişime geçin.', 'body': [
            ('p', 'Soru, öneri veya hata bildirimi mi var? Bize {email} adresinden yazın.'),
            ('p', 'Sorun bildirirken lütfen tarayıcınızı ve cihazınızı belirtin; mümkünse sonucun altındaki "Test ayrıntıları" kutusundaki metni yapıştırın. Nedeni hızlıca bulmamıza yardımcı olur.'),
            ('p', 'Her mesajı okuruz ancak internet sağlayıcınız veya modeminiz için destek veremeyiz.'),
        ]},
        'privacy': {'title': 'Gizlilik politikası', 'desc': '{site} verilerinizi nasıl işler: IP adresi, çerezler ve reklamlar.', 'body': [
            ('p', 'Bu politika, web sitesini kullandığınızda {site} tarafından hangi bilgilerin işlendiğini açıklar.'),
            ('h', 'İşlediğimiz bilgiler'),
            ('p', 'Siteyi açtığınızda IP adresinizi işleriz. Bunu size gösteririz ve internet sağlayıcınızı ile yaklaşık konumunuzu bulmak için kullanırız. Bu sorgu için IP adresiniz üçüncü taraf hizmetlere (ipapi.is, ipwho.is, ipapi.co) gönderilir. Sonuç sunucu belleğinde en fazla bir saat tutulur; veritabanına kaydedilmez ve kimliğinizle ilişkilendirilmez.'),
            ('h', 'Hız testi verileri'),
            ('p', 'Test, cihazınız ile sunucumuz arasında rastgele veri aktarır; bunların hiçbiri saklanmaz. Sonuçlar tarayıcınızda gösterilir ve yalnızca kopyala düğmesine basarsanız kopyalanır. Tarayıcınız Wi-Fi, kablo veya mobil veri kullandığınızı anlamak için yerel olarak WebRTC kullanabilir; hiçbir adres bir yere gönderilmez.'),
            ('h', 'Çerezler ve yerel depolama'),
            ('p', 'Dil ve tema seçiminizi tarayıcınızda saklarız (st_lang adlı bir çerez ile st_lang ve st_theme yerel depolama kayıtları). Yalnızca ayarlarınızı hatırlar, kişisel veri içermez.'),
            ('h', 'Reklamlar'),
            ('p', 'Reklam göstermek için Google AdSense kullanırız. Google ve iş ortakları, bu ve diğer sitelere yaptığınız ziyaretlere göre kişiselleştirilmiş veya kişiselleştirilmemiş reklamlar göstermek için çerez veya benzer teknolojiler kullanabilir. Google\'ın verileri nasıl kullandığını https://policies.google.com/technologies/partner-sites adresinden öğrenebilir, reklam kişiselleştirmesini https://adssettings.google.com adresinden yönetebilirsiniz. Avrupa Ekonomik Alanı, Birleşik Krallık ve İsviçre\'den gelen ziyaretçilerden kişiselleştirilmiş reklamlar gösterilmeden önce onay istenir.'),
            ('h', 'Sunucu kayıtları'),
            ('p', 'Barındırma sağlayıcımız güvenlik ve hizmetin işletilmesi için standart sunucu kayıtları (IP adresi, zaman ve istenen sayfa) tutabilir.'),
            ('h', 'Haklarınız'),
            ('p', 'Yaşadığınız yere bağlı olarak kişisel verilerinize erişme, düzeltme, silme veya işlenmesine itiraz etme hakkınız olabilir. {email} adresinden bize ulaşın, yanıt veririz.'),
            ('h', 'Çocuklar'),
            ('p', 'Site 13 yaşın altındaki çocuklara yönelik değildir ve onların verilerini bilerek toplamayız.'),
            ('h', 'Değişiklikler'),
            ('p', 'Bu politikayı güncelleyebiliriz. En üstteki tarih son sürümü gösterir.'),
        ]},
        'terms': {'title': 'Kullanım koşulları', 'desc': '{site} internet hız testini kullanma koşulları.', 'body': [
            ('p', '{site} sitesini kullanarak bu koşulları kabul etmiş olursunuz.'),
            ('h', 'Hizmet'),
            ('p', 'Hız testi ücretsiz ve "olduğu gibi" sunulur; erişilebilirlik veya doğruluk garantisi verilmez.'),
            ('h', 'Sonuçların doğruluğu'),
            ('p', 'Sonuçlar cihazınıza, tarayıcınıza, Wi-Fi kalitenize, sağlayıcınıza ve sunucumuza olan mesafeye bağlıdır. Cihazınız ile sunucumuz arasındaki hızı gösterir ve diğer araçlardan farklı olabilir. Sağlayıcınızın performansı için hukuki delil olarak kullanılmamalıdır.'),
            ('h', 'Kabul edilebilir kullanım'),
            ('p', 'Hizmeti aşırı yüklemek veya bant genişliği tüketmek için betik, bot veya tekrarlı istek kullanmayın. Hizmeti korumak için her bağlantının saatte kullanabileceği test verisi miktarını sınırlarız ve kötüye kullanan trafiği engelleyebiliriz.'),
            ('h', 'Reklamlar ve bağlantılar'),
            ('p', 'Site üçüncü taraf reklamlar gösterir. Reklamverenlerin veya bağlantılı sitelerin içeriğinden ve uygulamalarından sorumlu değiliz.'),
            ('h', 'Sorumluluk'),
            ('p', 'Yasaların izin verdiği ölçüde {site}, hizmetin kullanımından veya kullanılamamasından doğan hiçbir kayıptan sorumlu değildir.'),
            ('h', 'Değişiklikler'),
            ('p', 'Bu koşulları istediğimiz zaman değiştirebiliriz. Kullanmaya devam etmeniz güncel koşulları kabul ettiğiniz anlamına gelir.'),
        ]},
    },
}

# ------------------------------------------------------------------ FRENCH
T['fr'] = {
    'title': 'Test de débit Internet - Téléchargement, envoi et ping gratuits',
    'desc': 'Testez votre débit Internet en 30 secondes environ. Test gratuit et précis du téléchargement, de l\'envoi, du ping et de la gigue, avec votre IP, votre fournisseur et votre type de connexion.',
    'h1': 'Test de débit Internet',
    'sub': 'Mesurez votre débit descendant, montant, le ping et la gigue en 30 secondes environ.',
    'nav': {'home': 'Test de débit', 'about': 'À propos', 'privacy': 'Politique de confidentialité', 'terms': 'Conditions d\'utilisation', 'contact': 'Contact'},
    'ui': {'skip': 'Aller au contenu', 'ad': 'Publicité', 'rights': 'Tous droits réservés', 'server': 'Serveur', 'lang': 'Langue',
           'to_light': 'Passer en mode clair', 'to_dark': 'Passer en mode sombre', 'updated': 'Dernière mise à jour', 'back': 'Retour au test de débit',
           'notfound': 'Page introuvable', 'notfound_p': 'La page que vous cherchez n\'existe pas.', 'menu': 'Menu'},
    'guide_title': 'Comprendre le résultat du test',
    'guide': [
        ('Que signifient le téléchargement et l\'envoi en Mbps ?',
         'Le débit se mesure en mégabits par seconde (Mbps). Le téléchargement est la vitesse à laquelle les données arrivent sur votre appareil : il compte pour le streaming, la navigation et les téléchargements. L\'envoi est la vitesse à laquelle votre appareil émet des données : il compte pour les appels vidéo, les sauvegardes dans le cloud et l\'envoi de gros fichiers.'),
        ('Que sont le ping et la gigue ?',
         'Le ping est le temps, en millisecondes (ms), qu\'un petit message met pour aller au serveur et revenir. La gigue est la variation de ce temps d\'un message à l\'autre. Un ping et une gigue faibles donnent une connexion réactive pour les jeux, les appels et le télétravail. Moins de 50 ms convient à la plupart des usages ; une gigue sous 10 ms est très stable.'),
        ('De quel débit ai-je besoin ?',
         'Environ 5 Mbps suffisent pour la HD sur un écran, 15 à 25 Mbps pour la 4K, et 25 à 50 Mbps pour un foyer chargé en appels vidéo et en jeu cloud. Pour télétravailler, un débit montant d\'au moins 10 Mbps garde les visioconférences fluides.'),
        ('Comment obtenir le résultat le plus précis',
         'Fermez les autres applications et téléchargements, suspendez le streaming sur les autres appareils, rapprochez-vous du routeur ou utilisez un câble. Lancez le test deux ou trois fois et comparez. Ce test mesure le débit entre votre appareil et notre serveur ; le résultat peut donc différer un peu d\'autres outils qui utilisent d\'autres serveurs.'),
    ],
    'faq_title': 'Questions fréquentes',
    'faq': [
        ('Ce test de débit est-il gratuit ?', 'Oui. Le test est entièrement gratuit et ne demande ni inscription ni application.'),
        ('Pourquoi mon débit est-il inférieur à celui promis par mon fournisseur ?', 'Les fournisseurs annoncent le meilleur débit de votre forfait. La qualité du Wi-Fi, la distance au routeur, les heures de pointe, les appareils anciens et l\'emplacement du serveur peuvent le réduire. Un test par câble montre ce que votre ligne délivre réellement.'),
        ('Quelle quantité de données le test consomme-t-il ?', 'Un test complet peut consommer environ 100 à 300 Mo sur une connexion rapide, moins sur une connexion lente. Avec un forfait mobile limité, ne le lancez que si nécessaire.'),
        ('Le site peut-il voir le nom de mon Wi-Fi ?', 'Non. Les navigateurs ne permettent à aucun site de lire le nom du Wi-Fi. Le site affiche votre adresse IP, votre fournisseur et votre position approximative, et détecte si vous êtes en Wi-Fi, en câble ou en données mobiles lorsque votre navigateur le permet.'),
    ],
    'pages': {
        'about': {'title': 'À propos - {site}', 'desc': 'Ce qu\'est {site} et comment fonctionne le test de débit Internet.', 'body': [
            ('p', '{site} est un test de débit Internet gratuit. Il mesure le téléchargement, l\'envoi, le ping et la gigue, et affiche votre adresse IP, votre fournisseur, votre position approximative et votre type de connexion.'),
            ('h', 'Comment fonctionne le test'),
            ('p', 'Le test mesure d\'abord la latence avec de petites requêtes. Il ouvre ensuite six connexions parallèles vers notre serveur et transfère des données aléatoires : d\'abord en téléchargement, puis en envoi. Les premières secondes sont ignorées car les connexions montent encore en régime ; le chiffre final est le débit moyen ensuite. Le cadran affiche la vitesse en direct pendant le test.'),
            ('h', 'Qui exploite le site'),
            ('p', 'Le site est exploité par {operator}. Il est gratuit et financé par la publicité. Nous ne vendons pas de données personnelles.'),
            ('h', 'Langues et apparence'),
            ('p', 'Le site est disponible en arabe, anglais, turc, français et persan, avec un mode clair et un mode sombre.'),
        ]},
        'contact': {'title': 'Contact', 'desc': 'Contactez l\'équipe {site} pour une question, un bug ou une demande professionnelle.', 'body': [
            ('p', 'Une question, une suggestion ou un bug ? Écrivez-nous à {email}.'),
            ('p', 'Pour signaler un problème, indiquez votre navigateur et votre appareil et, si possible, collez le texte de la zone « Détails du test » sous votre résultat. Cela nous aide à trouver la cause rapidement.'),
            ('p', 'Nous lisons tous les messages mais ne pouvons pas assurer le support de votre fournisseur ou de votre routeur.'),
        ]},
        'privacy': {'title': 'Politique de confidentialité', 'desc': 'Comment {site} traite vos données : adresse IP, cookies et publicité.', 'body': [
            ('p', 'Cette politique explique quelles informations {site} traite lorsque vous utilisez le site.'),
            ('h', 'Informations traitées'),
            ('p', 'Lorsque vous ouvrez le site, nous traitons votre adresse IP. Nous vous l\'affichons et l\'utilisons pour retrouver votre fournisseur d\'accès et votre position approximative. Pour cette recherche, votre adresse IP est envoyée à des services tiers (ipapi.is, ipwho.is, ipapi.co). Le résultat est conservé en mémoire du serveur jusqu\'à une heure ; il n\'est pas enregistré dans une base de données ni lié à votre identité.'),
            ('h', 'Données du test de débit'),
            ('p', 'Le test transfère des données aléatoires entre votre appareil et notre serveur ; rien n\'est conservé. Les résultats s\'affichent dans votre navigateur et ne sont copiés que si vous appuyez sur le bouton de copie. Votre navigateur peut utiliser WebRTC en local pour savoir si vous êtes en Wi-Fi, en câble ou en données mobiles ; aucune adresse n\'est envoyée.'),
            ('h', 'Cookies et stockage local'),
            ('p', 'Nous enregistrons votre choix de langue et de thème dans votre navigateur (un cookie nommé st_lang et les entrées de stockage local st_lang et st_theme). Ils ne servent qu\'à mémoriser vos réglages et ne contiennent aucune donnée personnelle.'),
            ('h', 'Publicité'),
            ('p', 'Nous utilisons Google AdSense pour afficher des annonces. Google et ses partenaires peuvent utiliser des cookies ou des technologies similaires pour afficher des annonces personnalisées ou non, selon vos visites sur ce site et d\'autres. Vous pouvez savoir comment Google utilise les données sur https://policies.google.com/technologies/partner-sites et gérer la personnalisation des annonces sur https://adssettings.google.com. Les visiteurs de l\'Espace économique européen, du Royaume-Uni et de la Suisse sont invités à donner leur consentement avant l\'affichage d\'annonces personnalisées.'),
            ('h', 'Journaux du serveur'),
            ('p', 'Notre hébergeur peut conserver des journaux de serveur standard (adresse IP, heure et page demandée) pour la sécurité et l\'exploitation du service.'),
            ('h', 'Vos droits'),
            ('p', 'Selon votre lieu de résidence, vous pouvez avoir le droit d\'accéder à vos données personnelles, de les corriger, de les supprimer ou de vous opposer à leur traitement. Écrivez-nous à {email}.'),
            ('h', 'Enfants'),
            ('p', 'Le site ne s\'adresse pas aux enfants de moins de 13 ans et nous ne collectons pas sciemment leurs données.'),
            ('h', 'Modifications'),
            ('p', 'Nous pouvons mettre à jour cette politique. La date en haut indique la dernière version.'),
        ]},
        'terms': {'title': 'Conditions d\'utilisation', 'desc': 'Conditions d\'utilisation du test de débit Internet de {site}.', 'body': [
            ('p', 'En utilisant {site}, vous acceptez ces conditions.'),
            ('h', 'Le service'),
            ('p', 'Le test de débit est fourni gratuitement et « en l\'état », sans garantie de disponibilité ni de précision.'),
            ('h', 'Précision des résultats'),
            ('p', 'Les résultats dépendent de votre appareil, de votre navigateur, de la qualité du Wi-Fi, de votre fournisseur et de la distance à notre serveur. Ils montrent le débit entre votre appareil et notre serveur et peuvent différer d\'autres outils. Ils ne doivent pas servir de preuve juridique des performances de votre fournisseur.'),
            ('h', 'Utilisation acceptable'),
            ('p', 'N\'utilisez pas de scripts, de robots ni de requêtes répétées pour surcharger le service ou consommer de la bande passante. Pour protéger le service, nous limitons la quantité de données de test utilisable par connexion et par heure, et nous pouvons bloquer le trafic abusif.'),
            ('h', 'Publicité et liens'),
            ('p', 'Le site affiche des annonces de tiers. Nous ne sommes pas responsables du contenu ni des pratiques des annonceurs ou des sites liés.'),
            ('h', 'Responsabilité'),
            ('p', 'Dans la mesure permise par la loi, {site} n\'est responsable d\'aucune perte résultant de l\'utilisation du service ou de l\'impossibilité de l\'utiliser.'),
            ('h', 'Modifications'),
            ('p', 'Nous pouvons modifier ces conditions à tout moment. La poursuite de l\'utilisation vaut acceptation des conditions mises à jour.'),
        ]},
    },
}

# ------------------------------------------------------------------ PERSIAN
T['fa'] = {
    'title': 'تست سرعت اینترنت - تست رایگان دانلود، آپلود و پینگ',
    'desc': 'سرعت اینترنت خود را در حدود 30 ثانیه بسنجید. تست رایگان و دقیق دانلود، آپلود، پینگ و جیتر همراه با نمایش IP، ارائه‌دهنده و نوع اتصال.',
    'h1': 'تست سرعت اینترنت',
    'sub': 'سرعت دانلود، آپلود، پینگ و جیتر را در حدود 30 ثانیه اندازه بگیرید.',
    'nav': {'home': 'تست سرعت', 'about': 'درباره ما', 'privacy': 'سیاست حریم خصوصی', 'terms': 'شرایط استفاده', 'contact': 'تماس با ما'},
    'ui': {'skip': 'رفتن به محتوا', 'ad': 'تبلیغ', 'rights': 'تمامی حقوق محفوظ است', 'server': 'سرور', 'lang': 'زبان',
           'to_light': 'تغییر به حالت روشن', 'to_dark': 'تغییر به حالت تیره', 'updated': 'آخرین به‌روزرسانی', 'back': 'بازگشت به تست سرعت',
           'notfound': 'صفحه پیدا نشد', 'notfound_p': 'صفحه‌ای که دنبالش هستید وجود ندارد.', 'menu': 'منو'},
    'guide_title': 'نتیجه تست سرعت را بهتر بشناسید',
    'guide': [
        ('سرعت دانلود و آپلود بر حسب Mbps یعنی چه؟',
         'سرعت با مگابیت بر ثانیه (Mbps) سنجیده می‌شود. سرعت دانلود یعنی داده با چه سرعتی به دستگاه شما می‌رسد و برای پخش ویدیو، مرور وب و دانلود فایل مهم است. سرعت آپلود یعنی دستگاه شما با چه سرعتی داده می‌فرستد و برای تماس تصویری، پشتیبان‌گیری ابری و ارسال فایل‌های بزرگ مهم است.'),
        ('پینگ و جیتر چیست؟',
         'پینگ مدت زمانی است (بر حسب میلی‌ثانیه، ms) که یک پیام کوچک تا سرور می‌رود و برمی‌گردد. جیتر میزان تغییر این زمان از یک پیام به پیام بعدی است. پینگ و جیتر کم در بازی، تماس و کار از راه دور اتصال روان‌تری می‌دهد. پینگ زیر 50 ms برای بیشتر کارها خوب است و جیتر زیر 10 ms یعنی اتصال بسیار پایدار.'),
        ('به چه سرعتی نیاز دارم؟',
         'حدود 5 Mbps برای ویدیوی HD روی یک صفحه کافی است، 15 تا 25 Mbps برای پخش 4K و 25 تا 50 Mbps برای خانه‌ای شلوغ با تماس تصویری و بازی ابری. برای کار از خانه، سرعت آپلود حداقل 10 Mbps جلسات تصویری را روان نگه می‌دارد.'),
        ('چگونه دقیق‌ترین نتیجه را بگیریم',
         'برنامه‌ها و دانلودهای دیگر را ببندید، پخش در دستگاه‌های دیگر را متوقف کنید، نزدیک مودم بنشینید یا از کابل استفاده کنید. تست را دو یا سه بار انجام دهید و مقایسه کنید. این تست سرعت بین دستگاه شما و سرور ما را می‌سنجد، بنابراین ممکن است با ابزارهایی که سرور دیگری دارند کمی تفاوت داشته باشد.'),
    ],
    'faq_title': 'پرسش‌های متداول',
    'faq': [
        ('آیا این تست سرعت رایگان است؟', 'بله. تست کاملاً رایگان است و نیازی به ثبت‌نام یا نصب برنامه ندارد.'),
        ('چرا سرعت من کمتر از وعده ارائه‌دهنده است؟', 'ارائه‌دهندگان بهترین سرعت بسته شما را اعلام می‌کنند. کیفیت وای‌فای، فاصله از مودم، ساعات شلوغی، دستگاه‌های قدیمی و محل سرور تست می‌تواند آن را کم کند. تست با کابل نشان می‌دهد خط شما واقعاً چه سرعتی دارد.'),
        ('این تست چقدر داده مصرف می‌کند؟', 'یک تست کامل روی اتصال سریع حدود 100 تا 300 مگابایت مصرف می‌کند و روی اتصال کند کمتر. اگر بسته اینترنت همراه محدود دارید فقط در صورت نیاز اجرا کنید.'),
        ('آیا سایت نام وای‌فای من را می‌بیند؟', 'خیر. مرورگرها به هیچ سایتی اجازه خواندن نام وای‌فای را نمی‌دهند. سایت آدرس IP، ارائه‌دهنده و موقعیت تقریبی شما را نشان می‌دهد و در جایی که مرورگر اجازه دهد تشخیص می‌دهد روی وای‌فای، کابل یا داده همراه هستید.'),
    ],
    'pages': {
        'about': {'title': 'درباره ما - {site}', 'desc': '{site} چیست و تست سرعت اینترنت چگونه کار می‌کند.', 'body': [
            ('p', '{site} یک تست سرعت اینترنت رایگان است. سرعت دانلود، آپلود، پینگ و جیتر را می‌سنجد و آدرس IP، ارائه‌دهنده اینترنت، موقعیت تقریبی و نوع اتصال شما را نشان می‌دهد.'),
            ('h', 'تست چگونه کار می‌کند'),
            ('p', 'تست ابتدا با درخواست‌های کوچک تأخیر را می‌سنجد. سپس شش اتصال موازی با سرور ما باز می‌کند و داده تصادفی منتقل می‌کند: اول دانلود و بعد آپلود. چند ثانیه اول نادیده گرفته می‌شود چون اتصال‌ها هنوز گرم نشده‌اند و عدد نهایی میانگین سرعت پس از آن است. صفحه‌نمایش گرد سرعت لحظه‌ای را در طول تست نشان می‌دهد.'),
            ('h', 'چه کسی آن را اداره می‌کند'),
            ('p', 'این سایت توسط {operator} اداره می‌شود. استفاده از آن رایگان است و با تبلیغات تأمین مالی می‌شود. ما داده شخصی نمی‌فروشیم.'),
            ('h', 'زبان‌ها و ظاهر'),
            ('p', 'سایت به زبان‌های عربی، انگلیسی، ترکی، فرانسوی و فارسی و با حالت روشن و تیره در دسترس است.'),
        ]},
        'contact': {'title': 'تماس با ما', 'desc': 'برای پرسش، گزارش مشکل یا همکاری با تیم {site} تماس بگیرید.', 'body': [
            ('p', 'پرسش، پیشنهاد یا گزارش مشکلی دارید؟ به نشانی {email} برای ما بنویسید.'),
            ('p', 'هنگام گزارش مشکل، مرورگر و دستگاه خود را بنویسید و در صورت امکان متن کادر «جزئیات تست» زیر نتیجه را بچسبانید. این کار به ما کمک می‌کند علت را سریع پیدا کنیم.'),
            ('p', 'همه پیام‌ها را می‌خوانیم اما نمی‌توانیم برای ارائه‌دهنده اینترنت یا مودم شما پشتیبانی کنیم.'),
        ]},
        'privacy': {'title': 'سیاست حریم خصوصی', 'desc': 'نحوه برخورد {site} با داده‌های شما: آدرس IP، کوکی‌ها و تبلیغات.', 'body': [
            ('p', 'این سیاست توضیح می‌دهد هنگام استفاده از وب‌سایت، {site} چه اطلاعاتی را پردازش می‌کند.'),
            ('h', 'اطلاعاتی که پردازش می‌کنیم'),
            ('p', 'هنگام باز کردن سایت، آدرس IP شما را پردازش می‌کنیم. آن را به شما نشان می‌دهیم و برای پیدا کردن ارائه‌دهنده اینترنت و موقعیت تقریبی به کار می‌بریم. برای این جستجو، آدرس IP شما به سرویس‌های شخص ثالث (ipapi.is، ipwho.is، ipapi.co) ارسال می‌شود. نتیجه تا حداکثر یک ساعت در حافظه سرور نگه داشته می‌شود و در پایگاه داده ذخیره یا به هویت شما مرتبط نمی‌شود.'),
            ('h', 'داده‌های تست سرعت'),
            ('p', 'تست داده تصادفی بین دستگاه شما و سرور ما منتقل می‌کند و چیزی از آن ذخیره نمی‌شود. نتایج در مرورگر شما نمایش داده می‌شود و فقط با فشردن دکمه کپی، کپی می‌شود. مرورگر شما ممکن است برای تشخیص وای‌فای، کابل یا داده همراه به‌صورت محلی از WebRTC استفاده کند و هیچ آدرسی ارسال نمی‌شود.'),
            ('h', 'کوکی‌ها و حافظه محلی'),
            ('p', 'انتخاب زبان و پوسته شما را در مرورگرتان نگه می‌داریم (کوکی st_lang و موارد st_lang و st_theme در حافظه محلی). این‌ها فقط تنظیمات شما را به یاد می‌آورند و داده شخصی ندارند.'),
            ('h', 'تبلیغات'),
            ('p', 'برای نمایش تبلیغات از Google AdSense استفاده می‌کنیم. گوگل و شرکای آن ممکن است از کوکی یا فناوری‌های مشابه برای نمایش تبلیغات شخصی‌سازی‌شده یا غیرشخصی بر اساس بازدیدهای شما از این سایت و سایت‌های دیگر استفاده کنند. می‌توانید نحوه استفاده گوگل از داده‌ها را در https://policies.google.com/technologies/partner-sites ببینید و شخصی‌سازی تبلیغات را در https://adssettings.google.com مدیریت کنید. از بازدیدکنندگان منطقه اقتصادی اروپا، بریتانیا و سوئیس پیش از نمایش تبلیغات شخصی‌سازی‌شده رضایت گرفته می‌شود.'),
            ('h', 'گزارش‌های سرور'),
            ('p', 'ارائه‌دهنده میزبانی ما ممکن است برای امنیت و اداره سرویس گزارش‌های معمول سرور (آدرس IP، زمان و صفحه درخواستی) نگه دارد.'),
            ('h', 'حقوق شما'),
            ('p', 'بسته به محل زندگی‌تان ممکن است حق دسترسی، اصلاح یا حذف داده‌های شخصی یا اعتراض به پردازش آن را داشته باشید. به {email} پیام دهید تا پاسخ دهیم.'),
            ('h', 'کودکان'),
            ('p', 'این سایت برای کودکان زیر 13 سال نیست و آگاهانه داده آن‌ها را جمع‌آوری نمی‌کنیم.'),
            ('h', 'تغییرات'),
            ('p', 'ممکن است این سیاست را به‌روزرسانی کنیم. تاریخ بالای صفحه آخرین نسخه را نشان می‌دهد.'),
        ]},
        'terms': {'title': 'شرایط استفاده', 'desc': 'شرایط استفاده از تست سرعت اینترنت {site}.', 'body': [
            ('p', 'با استفاده از {site} این شرایط را می‌پذیرید.'),
            ('h', 'خدمت'),
            ('p', 'تست سرعت رایگان و «به همان صورت که هست» ارائه می‌شود و هیچ تضمینی برای دسترسی یا دقت وجود ندارد.'),
            ('h', 'دقت نتایج'),
            ('p', 'نتایج به دستگاه، مرورگر، کیفیت وای‌فای، ارائه‌دهنده و فاصله تا سرور ما بستگی دارد. آن‌ها سرعت بین دستگاه شما و سرور ما را نشان می‌دهند و ممکن است با ابزارهای دیگر فرق کنند. نباید به‌عنوان مدرک حقوقی عملکرد ارائه‌دهنده شما استفاده شوند.'),
            ('h', 'استفاده مجاز'),
            ('p', 'برای فشار آوردن بر سرویس یا مصرف پهنای باند از اسکریپت، ربات یا درخواست‌های مکرر استفاده نکنید. برای حفاظت از سرویس، مقدار داده تستی را که هر اتصال در ساعت می‌تواند مصرف کند محدود می‌کنیم و ممکن است ترافیک سوءاستفاده‌گر را مسدود کنیم.'),
            ('h', 'تبلیغات و پیوندها'),
            ('p', 'سایت تبلیغات اشخاص ثالث نمایش می‌دهد. ما مسئول محتوا یا رویه تبلیغ‌دهندگان و سایت‌های پیوندشده نیستیم.'),
            ('h', 'مسئولیت'),
            ('p', 'تا حدی که قانون اجازه می‌دهد، {site} مسئول هیچ زیانی ناشی از استفاده یا عدم امکان استفاده از سرویس نیست.'),
            ('h', 'تغییرات'),
            ('p', 'ممکن است هر زمان این شرایط را تغییر دهیم. ادامه استفاده به معنای پذیرش شرایط به‌روز است.'),
        ]},
    },
}
